### ISSUE TITLE
Proto type int64 get the error format in http swagger post body

### ISSUE THREAD

**Issue by zengzhengrong** [utrack/clay#91]
proto file
```
message Userprofile{
  int64 user_id = 1;
  ...
 }
```
pb.go
```
type Userprofile struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
  ....
}
```
![{8CE3E2BC-BF98-4D2F-BC36-BFE9087C216E}_20200616155100](https://user-images.githubusercontent.com/23110784/84748933-e3aa8500-afeb-11ea-9936-15fa27816b11.jpg)
It’s very strange ~, but I try to use int32 , it's work fine

**Comment by utrack** [comment]
Hi, it is not an error and in fact a Protobuf JSON mapping spec: https://developers.google.com/protocol-buffers/docs/proto3#json_mapping

It is done like that because JS integers are precise up to 2^52 instead of int64's 2^63: https://github.com/grpc-ecosystem/grpc-gateway/issues/219#issuecomment-251250029

So if you were sending JSON of `{"foo":(number bigger than 2^52)}` many JSON parsers won't parse that number.

**Comment by bullgare** [comment]
Yes, we've run into this limitation a couple of years ago also.

**Comment by zengzhengrong** [comment]
Thank ~！ Got it
